swagger: '2.0'
info:
  title: Coding-Assessment (Google APIs)
  version: 1.0.0
  description: |-
    <b>Task 1: Swagger Open API Specifications</b>
    
    This open API spec includes 5 API endpoints for Google Cloud Storage APIs as mentioned below:
    1. Generating OAuth2 Token for authenticating to GCP and using GCP APIs.
    2. Getting all objects and their meta data from GCP storage bucket
    3. Uploading new object (file) to GCP storage bucket
    4. Copying/Cloning the object from source bucket to destination bucket with renaming
    5. Deleting the object from cloud storage bucket

    _Note: This Open API Specification is built keepting `Postman Collection` as base. This postman collection is available under the `GitHub repository` for reference._
    
    Link to Postman Collection:
    - [Coding-Assessment-Postman-Collection](https://github.com/thesrishtisharma/Coding-Assessment/tree/master/1.%20Postman%20Collection)
    ___________________________________________________________________________

  contact:
    email: imsrishtisharma@gmail.com
host: storage.googleapis.com
basePath: /
schemes:
  - https
paths:
  /storage/v1/b/srishti-bucket-01/o:
    get:
      parameters:
        - in: header
          name: Authorization
          type: string
          required: true
          description: Bearer access_token
        
      responses:
        '200':
          description: ''
      description: 1. Get All Objects from bucket using OAuth
      operationId: 1GetAllObjectsFromBucketUsingOauth
      summary: 1. Get All Objects from bucket using OAuth
  /storage/v1/b/srishti-bucket-01/o/stacy-copy.png:
    delete:
      parameters:
        - in: header
          name: Content-Length
          type: string
      responses:
        '200':
          description: ''
      description: 4. Delete the copied object
      operationId: 4DeleteTheCopiedObject
      summary: 4. Delete the copied object
  /storage/v1/b/srishti-bucket-01/o/stacy.png/rewriteTo/b/srishti-bucket-01/o/stacy-copy.png:
    post:
      consumes:
        - application/json
      parameters:
        - in: header
          name: Content-Length
          type: string
        - in: body
          name: body
          schema:
            properties:
              rewriteToken:
                example: ya29.a0AfB_byBPqwVnPVuMrgF6gRL9jSSWnyQNbCjFkBWj7Aclbe6-azZ2SXeUDk9bILjfaqI4YoE2H3VRiymZJ0NrrOljOZyA0LQ0w8hQWzLYdD9s-LABExth5sjg7zWeDuTibHieQ5fsc4c2KH1Mt08XuFX2OirBEpHzYgOnZQaCgYKAe0SARISFQHsvYlsmK_94lu_A6oB-pJ-kk0d9w0173
                type: string
            type: object
      responses:
        '200':
          description: ''
      description: 3. Copy the created object
      operationId: 3CopyTheCreatedObject
      summary: 3. Copy the created object
  /upload/storage/v1/b/srishti-bucket-01/o:
    post:
      consumes:
        - application/octet-stream
      parameters:
        - in: query
          name: uploadType
          type: string
        - in: query
          name: name
          type: string
        - in: body
          name: body
          schema:
            format: binary
            type: string
      responses:
        '200':
          description: ''
      description: 2. Uploading new object to bucket
      operationId: 2UploadingNewObjectToBucket
      summary: 2. Uploading new object to bucket
tags: []
